export const API = {
  auth: {
    signUp: '/api/auth/sign-up',
    signIn: '/api/auth/sign-in',
    uniqueEmail: '/api/auth/unique-email',
    validateEmail: '/api/auth/validate-email',
    google: '/api/auth/google',
    resetPassword: '/api/auth/password',
    updatePassword: '/api/auth/password',
    deactivateAccount: (userId: number) => `/api/auth/deactivate-account/${userId}`,
  },
  wishes: {
    create: '/api/wish',
    update: '/api/wish',
    deposit: '/api/wish/deposit',
    addToWishList: '/api/wish/add-to-wish-list',
    getWish: (wishId: number) => `/api/wish/${wishId}`,
    getImage: (wishId: number) => `/api/wish/${wishId}/img`,
    delete: (wishId: number) => `/api/wish/${wishId}`,
    deleteFromWishList: '/api/wish/delete-from-wish-list',
  },
  wishLists: {
    create: '/api/wish-list',
    update: '/api/wish-list',
    delete: (wishListId: number) => `/api/wish-list/${wishListId}`,
  },
  friends: {
    sendRequest: '/api/friends',
    getFriends: (userId: number) => `/api/friends/${userId}`,
    getFriendRequests: (userId: number) => `/api/friends/requests/${userId}`,
    getAllUsers: (userId: number) => `/api/friends/${userId}/search`,
  },
  booking: {
    create: '/api/booking',
    getBooking: (bookingId: number) => `/api/booking/${bookingId}`,
    cancel: (wishId: number) => `/api/booking/${wishId}`,
  },
  profile: {
    getProfile: (userId: number) => `/api/profile/${userId}`,
    getWishes: (userId: number) => `/api/profile/${userId}/wishes`,
    getWishLists: (userId: number) => `/api/profile/${userId}/wish-lists`,
    getPiggyBanks: (userId: number) => `/api/profile/${userId}/piggy-banks`,
    getBookings: (userId: number) => `/api/profile/${userId}/bookings`,
    getBackground: (userId: number) => `/api/profile/background/${userId}`,
    getAvatar: (userId: number) => `/api/profile/avatar/${userId}`,
  },
  settings: {
    updateUsername: '/api/settings/username',
    updateTheme: '/api/settings/theme',
    updatePrivacy: '/api/settings/privacy',
    updateName: '/api/settings/name',
    updateGender: '/api/settings/gender',
    updateEmail: '/api/settings/email',
    updateColors: '/api/settings/colors',
    updateBirthDate: '/api/settings/birth-date',
    updateBackground: '/api/settings/background',
    updateAvatar: '/api/settings/avatar',
    sendHelpMessage: '/api/settings/help-message',
    getSettings: (userId: number) => `/api/settings/${userId}`,
  },
  currencies: {
    getCurrencies: '/api/currency',
  },
};

export const SUPPORT_BOT_URL = 'https://t.me/GiftifyHelpBot';
